# Generated by Django 3.0.3 on 2020-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please insert your full name', max_length=100, verbose_name="person's name")),
                ('age', models.PositiveIntegerField()),
                ('gender', models.BooleanField(help_text='Please insert your gender', verbose_name="person's gender")),
            ],
        ),
    ]
