# Generated by Django 3.0.3 on 2020-02-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
